# Generated by Django 4.2.6 on 2023-10-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plants", "0004_alter_plant_plant_img_alter_plantdetection_plant_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recomendation",
            name="additional_info",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="recomendation",
            name="chemical_control_1",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="recomendation",
            name="chemical_control_1_dosage",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="recomendation",
            name="chemical_control_2",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="recomendation",
            name="chemical_control_2_dosage",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="recomendation",
            name="chemical_control_3",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="recomendation",
            name="chemical_control_3_dosage",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="recomendation",
            name="chemical_control_4",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="recomendation",
            name="chemical_control_4_dosage",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="recomendation",
            name="chemical_control_5",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="recomendation",
            name="chemical_control_5_dosage",
            field=models.TextField(null=True),
        ),
    ]
