# Generated by Django 4.2.6 on 2023-10-24 04:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plants", "0005_alter_recomendation_additional_info_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plant",
            name="plant_img",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="plantdetection",
            name="plant_img",
            field=models.CharField(max_length=255),
        ),
    ]
