# Generated by Django 4.2.6 on 2023-10-26 17:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plants", "0006_alter_plant_plant_img_alter_plantdetection_plant_img"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
