# Generated by Django 4.2.6 on 2023-11-15 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("plants", "0008_detectionhistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="detectionhistory",
            name="recomendation",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="plants.recomendation",
            ),
            preserve_default=False,
        ),
    ]
