# Generated by Django 3.2 on 2023-11-15 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0009_detectionhistory_recomendation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recomendation',
            old_name='recomendation',
            new_name='recommendation',
        ),
    ]
