# Generated by Django 3.2 on 2023-11-15 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0010_rename_recomendation_recomendation_recommendation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detectionhistory',
            old_name='recomendation',
            new_name='recommendation',
        ),
        migrations.RenameField(
            model_name='recomendation',
            old_name='recommendation',
            new_name='recomendation',
        ),
    ]
